# Generated by Django 4.2.7 on 2025-12-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, help_text='Shaxsning ismi', max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(db_index=True, help_text='Shaxsning familiyasi', max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, help_text='Otasining ismi', max_length=100, null=True, verbose_name='Sharif')),
                ('passport_series', models.CharField(blank=True, db_index=True, help_text='Masalan: AB', max_length=20, null=True, verbose_name='Passport seriyasi')),
                ('passport_number', models.CharField(blank=True, help_text='Masalan: 1234567', max_length=20, null=True, verbose_name='Passport raqami')),
                ('birth_date', models.DateField(blank=True, help_text='Masalan: 1990-01-15', null=True, verbose_name="Tug'ilgan kun")),
                ('pinfl', models.CharField(blank=True, db_index=True, help_text='14 raqamli PINFL/JShIR kod', max_length=14, null=True, unique=True, verbose_name='PINFL (JShIR)')),
                ('position', models.CharField(blank=True, help_text='Masalan: Inspektor, Boshliq va hokazo', max_length=200, null=True, verbose_name='Lavozim')),
                ('district', models.CharField(blank=True, help_text='Qaysi tumanga biriktirilgan', max_length=200, null=True, verbose_name='Biriktirilgan tuman')),
                ('department', models.CharField(blank=True, help_text="Qaysi bo'limda ishlaydi", max_length=200, null=True, verbose_name="Bo'lim")),
                ('phone_number', models.CharField(blank=True, help_text='Masalan: +998901234567', max_length=20, null=True, verbose_name='Telefon raqami')),
                ('mahalla', models.CharField(blank=True, help_text='Qaysi mahallada istiqomat qiladi', max_length=200, null=True, verbose_name='Mahalla')),
                ('jeton_series', models.CharField(blank=True, help_text='Xizmat jetoni seriyasi', max_length=50, null=True, verbose_name='Jeton seriyasi')),
                ('photo', models.ImageField(blank=True, help_text='Shaxsning yuz rasmi (face login uchun)', null=True, upload_to='faces/', verbose_name='Rasm')),
                ('face_encoding', models.JSONField(blank=True, help_text="Face recognition uchun 128 o'lchamli vektor", null=True, verbose_name='Yuz kodlash')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqt")),
            ],
            options={
                'verbose_name': 'Shaxs',
                'verbose_name_plural': 'Shaxslar',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='emotion_app_last_na_01c8ba_idx'), models.Index(fields=['passport_series'], name='emotion_app_passpor_62c435_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_method', models.CharField(choices=[('face', 'Yuz orqali'), ('passport', 'Passport orqali')], max_length=20, verbose_name='Login usuli')),
                ('login_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Kirish vaqti')),
                ('login_photo', models.ImageField(blank=True, null=True, upload_to='login_photos/%Y/%m/%d/', verbose_name='Login vaqtidagi rasm')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('confidence', models.FloatField(blank=True, help_text='Face recognition uchun ishonch darajasi', null=True, verbose_name='Ishonch darajasi (%)')),
                ('success', models.BooleanField(default=True, verbose_name='Muvaffaqiyatli')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='emotion_app.person', verbose_name='Shaxs')),
            ],
            options={
                'verbose_name': 'Login Log',
                'verbose_name_plural': 'Login Loglari',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['-login_time'], name='emotion_app_login_t_ad1fda_idx'), models.Index(fields=['person', '-login_time'], name='emotion_app_person__9009a8_idx')],
            },
        ),
    ]
