# Generated by Django 4.2.7 on 2025-12-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Masalan: +998901234567', max_length=50, null=True, verbose_name='Telefon raqami'),
        ),
    ]
